name: Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
        # Checkout updated source code
      - uses: actions/checkout@v2
    
        # If the version has changed, create a new git tag for it.
      - name: Setup Dev Tooling
        id: setup
        run: |
          docker pull docker.pkg.github.com/author/dev/dev-base:1.17.2
          docker pull docker.pkg.github.com/author/dev/dev-node:14.8.0
          docker pull docker.pkg.github.com/author/dev/dev-deno:1.3.1
          docker pull docker.pkg.github.com/author/dev/dev-browser:5.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: actions/setup-node@v1
        if: steps.create_release.outputs.id != ''
        with:
          node-version: '14'

      - name: Test
        if: success()
        run: |
          npm test
